stickers={"Like": "CAACAgIAAxkBAANUYAsChozmbLV53PxaJBUUOAc55dQAAioAA9VBHQWJoxxxhg3WUx4E",
"Puppy": "CAACAgIAAxkBAANdYAsQicwLUwi3QIEiRESIhN9EUokAAqoFAALpVQUYAAEUi61_Fd-IHgQ",
"Sad": "CAACAgIAAxkBAANyYAsTU6REp0vH5ZFZMMCNkBD3h9YAAlsJAAJ5XOIJ5z5sFYhK9R8eBA",
"LoveBye": "CAACAgIAAxkBAAN7YAsUKXFdCzIeBGLUUS6wcmoeCLEAAmEAA05c0ilKY3GlTKlVbh4E"}